language: c
env:
  global:
  - PHARO_VERSION=70
addons:
  apt:
    packages:
    - libasound2:i386
    - libz1:i386
    - libbz2-1.0:i386
    - libssl1.0.0:i386
    - libfreetype6:i386

script:
 - "wget -O - get.pharo.org/${PHARO_VERSION}+vm | bash"
 - "./scripts/install-packages.sh"
 - "zip -r bootstrapImage Pharo.image Pharo.changes Pharo7.0*.sources"
 
deploy:
  provider: releases
  api_key:
    secure: b0VMRoFAQ/QZoXwVRQzDtvu5gzWkwWGLo8TxfYc7bmwzXLg8wQM1/FpKEjyfxH1pa5FYfcZ8n1U+QqdjQA9tYdmJzMZtrLIdK1cwrO3Eu+u9p1qMQ4w+xyWjg7oNmLhlSCJxGHt5FHfa2zm0yiZGrzFWW9TLhe61pfdAv+kUhll8Q6Bi5FkuYX1pSSP8NBrl64B42e7TyF8TznkHTg7NXBEr7cMTYNxBuBpHNSFrtf/Phm45bulp5ln20QRaymmTB5uQiGSEsE7Io8o6rOWgDIP/COxM+VeCbiw/5XwlaEfKYowCVoK6o1DvUoWTgw2iS1W7WQ70m4KV+xL5m73tguCIdHJbtm2BCC6ZYEKF+f5lF+dOQHzeJpx/9RKbjRFySXl+moNfkIaVVNLvVK5KvPh6k0f7RMCsa4TQPPdgvMeJnBbCFP5edqVJYbcRgEds9yIYOioaMQfKG3ZZJ6YHkHhh5spRitdWBjK9pYzxiRNS6miyhi/b+aB0kuLZ8HbkRoAXSt1oGTSrN7QrYE065WfjNHL2CGG8bOHDHAKIHuOw+AmBtLATuZPd1rgX3wtcxuZGm5at2zLwXnLxhktl9nVyKuHjwkgDfihQq1k7mobCfPcMsLZt2eP/78KOAFgL9Aaz0tUWV5Mf14MteMzOyg6mYfGXzTq9px02iRpRhR0=
  file: "bootstrapImage.zip"
  skip_cleanup: true
  on:
    repo: guillep/PharoBootstrap
    tags: true
